PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, uid TEXT UNIQUE NOT NULL, username TEXT, email TEXT UNIQUE, role TEXT DEFAULT 'user' NOT NULL, is_vip INTEGER DEFAULT 0, coins INTEGER DEFAULT 0, avatar_key TEXT, is_deleted INTEGER DEFAULT 0, last_daily_bonus INTEGER DEFAULT 0, daily_streak INTEGER DEFAULT 0, created_at INTEGER DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token TEXT UNIQUE NOT NULL, ip_address TEXT, user_agent TEXT, expires_at INTEGER NOT NULL, created_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS manhwa (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT, status TEXT DEFAULT 'ongoing', genres TEXT DEFAULT '[]', type TEXT DEFAULT 'manhwa', rating REAL DEFAULT 0.0, cover_key TEXT, banner_key TEXT, is_adult INTEGER DEFAULT 0, views INTEGER DEFAULT 0, created_at INTEGER DEFAULT (strftime('%s', 'now')), updated_at INTEGER DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS chapters (id TEXT PRIMARY KEY, manhwa_id TEXT NOT NULL, chapter_no REAL NOT NULL, title TEXT DEFAULT '', access_type TEXT DEFAULT 'free', coin_price INTEGER DEFAULT 0, status TEXT DEFAULT 'published', format TEXT DEFAULT 'webp', pdf_key TEXT, scheduled_at INTEGER, page_count INTEGER DEFAULT 0, created_at INTEGER DEFAULT (strftime('%s', 'now')), updated_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (manhwa_id) REFERENCES manhwa(id) ON DELETE CASCADE, UNIQUE(manhwa_id, chapter_no));
CREATE TABLE IF NOT EXISTS chapter_pages (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL, page_no INTEGER NOT NULL, image_key TEXT NOT NULL, width INTEGER, height INTEGER, FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE, UNIQUE(chapter_id, page_no));
CREATE TABLE IF NOT EXISTS banners (id TEXT PRIMARY KEY, media_key TEXT NOT NULL, media_type TEXT DEFAULT 'image', poster_key TEXT, slot TEXT DEFAULT 'home-hero', display_order INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, link_url TEXT, start_date INTEGER, end_date INTEGER, created_at INTEGER DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS media_assets (id TEXT PRIMARY KEY, r2_key TEXT UNIQUE NOT NULL, folder TEXT, mime_type TEXT, size INTEGER, created_at INTEGER DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS library (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, manhwa_id TEXT NOT NULL, status TEXT DEFAULT 'reading', last_chapter_id TEXT, created_at INTEGER DEFAULT (strftime('%s', 'now')), updated_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (manhwa_id) REFERENCES manhwa(id) ON DELETE CASCADE, UNIQUE(user_id, manhwa_id));
CREATE TABLE IF NOT EXISTS coin_transactions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, amount INTEGER NOT NULL, type TEXT NOT NULL, reference_id TEXT, note TEXT, created_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS promo_codes (id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, coin_amount INTEGER NOT NULL, max_uses INTEGER DEFAULT 1, current_uses INTEGER DEFAULT 0, expires_at INTEGER, created_by TEXT, created_at INTEGER DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS read_history (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, chapter_id TEXT NOT NULL, page_no INTEGER DEFAULT 1, scroll_position REAL DEFAULT 0.0, updated_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE, UNIQUE(user_id, chapter_id));
CREATE TABLE IF NOT EXISTS manhwa_ratings (user_id TEXT NOT NULL, manhwa_id TEXT NOT NULL, rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5), PRIMARY KEY (user_id, manhwa_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (manhwa_id) REFERENCES manhwa(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL, user_id TEXT NOT NULL, parent_id TEXT, text TEXT NOT NULL, is_spoiler INTEGER DEFAULT 0, likes INTEGER DEFAULT 0, created_at INTEGER DEFAULT (strftime('%s', 'now')), FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_manhwa_status ON manhwa(status);
CREATE INDEX IF NOT EXISTS idx_chapters_manhwa ON chapters(manhwa_id);
CREATE INDEX IF NOT EXISTS idx_pages_chapter ON chapter_pages(chapter_id);
