name = "azura-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "azura-db"
database_id = "19a7f08a-d22d-48bc-9952-c71534c0f769"

[[r2_buckets]]
binding = "R2"
bucket_name = "azura-media"

[triggers]
crons = ["*/15 * * * *"]
